---
title: "Logbook"
author: "Joshua Tolhuis"
date: "9/14/2021"
output: html_document
---  


---

##### Date : di 14 sep,  
- Created repository.  
- Chose a data set.
- Added log.  
- Checked  data set's documentation
- Added data file to repository (data gotten from [kaggle](https://www.kaggle.com/johnjdavisiv/urinary-biomarkers-for-pancreatic-cancer))
- Created an empty EDA file
- Added EDA file to repository
- Created a logbook to keep track of progression  

---

##### Date : wo 15 sep,
- Working from home (sick)
- Made some adjustments to the log
- Read the corresponding research paper
- Formulated a few questions to gain insight on a possible research question, or to look at in the EDA:
  * How is  REG1B	beter than	REG1A?
  * Can you predict Pancreatic ductal adenocarcinoma (PDAC) beter with REG1B than REG1A? 
  * How well can an algorythm predict PDAC with the improved biomarker?
  * Is it possible to use machine learning to predict PDAC (and its stages) with the biomarker? (same as John Davis)  
  * Does REG1B affect machine learning predictions for a beter outcome than REG1A?  
  * Can you predict the stages of PDAC with only using REG1B?
  
---

##### Date: di 21 sep,
- Figured out final research question:  
  "What's the minimal amount of data combinations to predict a patient has pancreatic ductal adenocarcinoma?"  
- Started work on the EDA and log, tried to combine several data values kind of like simple "oneR's".  
- Made a few plot's that I'm trying to use to get a better understanding of the biomarkers.
- Need to find out what makes these biomarkers relation to each other and the stages of PDAC.
- Need to create a boxplot with all 3 biomarkes and use this to determine the avere combined heights to find out a relation to this and the stage

---

##### Date: do 23 sep,
- made the box plot containing all 3 bio markers
- normalized data (need to apply to box plot)
- tried my hand at a PCA and a 3d PCA (plots work, no idea what they are comparing in the 2d pca)
- to do:
  * 3d PCA needs axis labels
  * figure out what 2d PCA does
  * normalize data for box plots
  * compare more oneR type plots
  * write intro's and conclusions into log
  * compile conclusions and plots in EDA
  
---

##### Date: su 26 sep,
- adding text to EDA
- added heatmap to log
- add axis labels to 3D PCA
- normilazed (scaled) data for boxplots
- removed outliers for some plots
- added regression lines

---

##### Date: Mo 27 sep,

- finishing touches, to log
- writing down everything into EDA
- submitting EDA